[package]
name = "whmcs"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies.tokio]
version = "1.52.3"
features = ["macros"]

[dependencies.url]
version = "2.5.8"

[dependencies.thiserror]
version = "2.0.18"

[dependencies.reqwest]
version = "0.13.3"
features = ["form", "json"]

[dependencies.serde]
version = "1.0.228"
features = ["derive"]

[dependencies.serde_json]
version = "1.0.149"

[dependencies.paste]
version = "1.0.15"

[dev-dependencies.dotenvy]
version = "0.15.7"

[dev-dependencies.temp-env]
version = "0.3.6"